/**
 * AUTO-GENERATED — DO NOT EDIT MANUALLY.
 *
 * This file is generated by running: pnpm gen:types
 * Command: supabase gen types typescript --local > packages/database-types/src/types.ts
 *
 * Any manual edits will be overwritten on the next generation run.
 * Update the database schema and re-run gen:types to reflect changes.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

// Placeholder — will be replaced with full generated types after T2 (Supabase schema).
export interface Database {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
